settings_generator: Change static_cast from float to double for point coordinates
This would cause an error in the CI because the LHS is a double.

/root/catkin_ws/build/zivid_camera/generated_headers/SettingsConfigUtils.h:110:42: error: implicit conversion increases floating-point precision: 'float' to 'double' [-Werror,-Wdouble-promotion]
  cfg.region_of_interest_box_point_a_y = static_cast<float>(s.get<Zivid::Settings::RegionOfInterest::Box::PointA>().value().y);